- hosts: all
  become: yes
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
  - name: Copy default apache page with static content
    ansible.builtin.copy:
      src: ./www/
      dest: /var/www/html/
  - name: Debug VM_ID
    tags:
      - debug
    ansible.builtin.debug:
      var: hostvars[inventory_hostname].VM_ID 
  - name: Replace VM_ID in apache apache
    ansible.builtin.replace:
      path: /var/www/html/index.html
      regexp: "%VM_ID%"
      replace: "{{ item }}"
    with_items:
      - "{{ hostvars[inventory_hostname].VM_ID }}"
